# Introduction
November 30th, 2023
EDAV
Professor Robbins

  Moneyball - How to win the Premier League
  (Tyler Freund, Yash Dange)

Background on our Data:
	
	The Premier League is the most prestigious and highest level of competitive
	soccer in England.  It is the most followed soccer league in the world,
	producing the biggest superstars in the sport and the strongest teams.  The
	premier league brought in over $6.9 billion dollars in revenue between
	2021-2022 and amassed over 4.7 billion viewers.  Given that this league is
	followed by such a large number of people and brings in such vast amounts of
	revenue, better understanding why and how certain teams excel is an incredibly
	fascinating and important topic.  We were able to gather a diverse collection
	of datasets that cover a wide range of details relating to the teams in this
	league.
 
Why you chose this topic:

	We wanted to find a dataset we were both passionate about and interested in.  
	After extensive searching and exploring of datasets we decided to use the
	premier league soccer datasets.  We chose these datasets because we both love
	sports and believe we can find meaningful trends in the data that help
	determine what makes a winning team.  By identifying characteristics of
	winning and losing teams we can help fans, investors, and teams themselves
	better understand what makes them successful.

Questions you are interested in studying: 

	As mentioned above, we want to discover what makes a winning team in the
	premier league. More concretely, we can research the attributes and statistics
	that are most highly correlated with winning and losing. For instance, do
	higher salaries mean a better chance of winning? How much more likely is a
	team to win based on a winning previous season? Are teams with a strong player
	in a certain position more likely to win? We delve into these questions and
	many more regarding how a team can become successful.
